services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    hostname: 10.150.49.146
    container_name: swagger_ui_container
    ports:
    - "8082:8080"
    volumes:
    - ./swagger:/usr/share/nginx/html/swagger
    environment:
      http_proxy:
      https_proxy:
      API_URL: swagger/swagger.yaml