# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import anomaly_pb2 as anomaly__pb2


class AnomalyDetectionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/pb.AnomalyDetection/Predict',
                request_serializer=anomaly__pb2.AnomalyRequest.SerializeToString,
                response_deserializer=anomaly__pb2.AnomalyResponse.FromString,
                )
        self.Train = channel.unary_unary(
                '/pb.AnomalyDetection/Train',
                request_serializer=anomaly__pb2.ModelTrainRequest.SerializeToString,
                response_deserializer=anomaly__pb2.ModelTrainResponse.FromString,
                )


class AnomalyDetectionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Train(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnomalyDetectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=anomaly__pb2.AnomalyRequest.FromString,
                    response_serializer=anomaly__pb2.AnomalyResponse.SerializeToString,
            ),
            'Train': grpc.unary_unary_rpc_method_handler(
                    servicer.Train,
                    request_deserializer=anomaly__pb2.ModelTrainRequest.FromString,
                    response_serializer=anomaly__pb2.ModelTrainResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.AnomalyDetection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AnomalyDetection(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.AnomalyDetection/Predict',
            anomaly__pb2.AnomalyRequest.SerializeToString,
            anomaly__pb2.AnomalyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.AnomalyDetection/Train',
            anomaly__pb2.ModelTrainRequest.SerializeToString,
            anomaly__pb2.ModelTrainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
