FROM golang:1.17-alpine
ENV http_proxy http://10.150.32.10:3128
ENV https_proxy http://10.150.32.10:3128
RUN apk update && apk add git
WORKDIR /go/delivery

COPY ./pb/*.go /usr/local/go/src/dxnnymurphy/gRPC/pb/
COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY client.go ./
COPY ./pb/anomaly.swagger.json ./
EXPOSE 8081

RUN go run client.go
